# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-03 16:37
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_geoprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Nome', max_length=40, null=True, verbose_name='Nome')),
                ('coords', django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326)),
                ('address', models.CharField(blank=True, help_text='Indirizzo', max_length=100, null=True, verbose_name='Indirizzo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.UserProfile')),
            ],
        ),
        migrations.RemoveField(
            model_name='geoprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='GeoProfile',
        ),
    ]
