# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-03 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20180503_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlocation',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserLocation',
        ),
    ]
