# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-04 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20180504_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Nome', max_length=40, null=True, verbose_name='Nome')),
                ('desc', models.CharField(blank=True, help_text='Descrizione', max_length=100, null=True, verbose_name='Descrizione')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='categories',
            field=models.ManyToManyField(to='locations.Category'),
        ),
    ]
