# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-08 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20180504_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='user',
            new_name='owner',
        ),
    ]
