# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-09 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20180508_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='categories',
            field=models.ManyToManyField(related_name='category', to='locations.Category'),
        ),
    ]
