# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-09 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_auto_20180509_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='location',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
